# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
### Assignment 1: Array Creation and Manipulation

### 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


import numpy as np

np_array = np.random.randint(1,21,(5,5))


In [2]:
print(np_array)

np_array[:,2] = 1

[[ 4 12  7  7  5]
 [ 6 13  5 18  7]
 [ 9 20  2 17 14]
 [18 15  3 13 17]
 [ 5  7  3 19  6]]


In [3]:
print(np_array)

[[ 4 12  1  7  5]
 [ 6 13  1 18  7]
 [ 9 20  1 17 14]
 [18 15  1 13 17]
 [ 5  7  1 19  6]]


In [4]:
np_4_4_aray = np.random.randint(1,16,(4,4))
np_4_4_aray

array([[12, 12, 10,  4],
       [ 3,  9, 15,  2],
       [12, 14, 15,  6],
       [14, 12,  8,  3]])

In [5]:
np.fill_diagonal(np_4_4_aray,0,wrap=True)
np_4_4_aray

array([[ 0, 12, 10,  4],
       [ 3,  0, 15,  2],
       [12, 14,  0,  6],
       [14, 12,  8,  0]])

In [6]:
# Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [7]:
np_6 = np.arange(1,37).reshape(6,6)
print("Original Array \n",np_6)
sub_array = np_6[2:5,1:4]
print("Sub array \n",sub_array)

Original Array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub array 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [8]:
# (5,5) array
np_5 = np.random.randint(1,100,(5,5))
print("5, 5 array \n\n", np_5)
print(np.concatenate([np_5[0,:],np_5[1:-1,-1],np_5[-1,::-1], np_5[1:-1,0][::-1]]))

5, 5 array 

 [[ 2 77 78 42  3]
 [61 93 37 42 62]
 [ 5 81 60 41 95]
 [11 51 44 40 47]
 [61 66 17 71 26]]
[ 2 77 78 42  3 62 95 47 26 71 17 66 61 11  5 61]


In [9]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [10]:
# Create two array of shape (3,4)
arr_1 = np.random.randint(1,10,(3,4))
arr_2 = np.random.randint(1,10,(3,4))

print(arr_1,'\n\n',arr_2)

[[4 9 6 7]
 [3 9 3 8]
 [9 7 4 9]] 

 [[6 2 4 5]
 [4 4 9 8]
 [7 3 8 5]]


In [11]:
array_sum = arr_1+arr_2
array_diff = arr_1-arr_2
array_multiply = arr_1*arr_2
array_divide = arr_1/arr_2
print(array_multiply)

[[24 18 24 35]
 [12 36 27 64]
 [63 21 32 45]]


In [12]:
# 4,4 array and row-wise and column wise sum.
arr_3 = np.random.randint(1,10,(4,4))
print(arr_3)
print('row wise sum \n', arr_3.sum(axis=1))
print('Column wise sum \n', arr_3.sum(axis=0))

[[4 1 1 9]
 [9 8 6 7]
 [7 6 7 1]
 [8 8 3 7]]
row wise sum 
 [15 30 21 26]
Column wise sum 
 [28 23 17 24]


In [13]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

# 1 
np_4 = np.random.randint(1,10,(5,5))
print('Mean -- ',np.mean(np_4))
print('Median -- ',np.median(np_4))
print('Standerd Deviation -- ',np.std(np_4))
print('Variance -- ',np.var(np_4))

Mean --  5.88
Median --  5.0
Standerd Deviation --  2.3549097647256043
Variance --  5.5456


In [14]:
# 2

In [15]:
np_5 = np.arange(1,10).reshape(3,3)
np5mean = np.mean(np_5)
standerdDeviation = np.std(np_5)
normalized_array = (np_5-np5mean)/standerdDeviation
print(np.std(normalized_array))

1.0


In [16]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


np_3_3 = np.random.randint(1,90,(3,3))
add_arr = [1,2,3]
print(np_3_3)
print(np_3_3 + add_arr)

# Subtract
print(np_3_3 - add_arr)

[[85  7 28]
 [22 60 24]
 [26 52 27]]
[[86  9 31]
 [23 62 27]
 [27 54 30]]
[[84  5 25]
 [21 58 21]
 [25 50 24]]


In [17]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

determinant = np.linalg.det(np_3_3)
inverse = np.linalg.inv(np_3_3)
eigenvalues = np.linalg.eigvals(np_3_3)
print("determinant -> ",determinant,'\n')
print("Inverse ---",inverse,'\n')
print("Eigen Value ",eigenvalues,'\n')

determinant ->  20182.000000000007 

Inverse --- [[ 0.01843227  0.06277871 -0.07491824]
 [ 0.00148647  0.07764344 -0.07055792]
 [-0.02061243 -0.2099891   0.24506986]] 

Eigen Value  [112.28200619  56.5388741    3.17911972] 



In [18]:
a23 = np.arange(1,7).reshape(2,3)
a32 = np.arange(1,7).reshape(3,2)

multiply = np.dot(a23,a32)

print(multiply)


[[22 28]
 [49 64]]


In [19]:
#  Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
a33 = np.arange(1,10).reshape(3,3)
reshape_1x9 = a33.reshape(1,9)
reshape_9x1 = a33.reshape(9,1)
arr_5X5 = np.random.randint(1,10,(5,5))
flatten = arr_5X5.flatten()
reshapeback = flatten.reshape(5,5)
print(reshapeback)

[[1 8 1 9 4]
 [2 7 3 9 4]
 [3 5 9 6 9]
 [6 2 9 1 8]
 [1 8 2 1 9]]


In [ ]:
# Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
a_5X5 = np.random.randint(1,10,(5,5))
# print(a_5X5)
# print(a_5X5[[0,0,-1,-1],[0,-1,0,-1]])
a_5X5[a_5X5>7] = 7
# print("Boolean indexing",a_5X5)
boolMask = a_5X5 > 5
# print("Bool Mask\n",boolMask)

Bool Mask
 [[False  True  True False False]
 [False False False  True  True]
 [ True  True  True  True False]
 [ True False  True False  True]
 [False False False False False]]


In [ ]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
strArr = np.dtype([
    ('name', 'U10'),
    ('age', 'i4'),
    ('weight', 'f8')
])

basicData = np.array([
    ('Vivek',28,64.5),
    ('Sunny',29,50.56)
], dtype = strArr)
print(basicData)


AttributeError: module 'numpy' has no attribute 'basicDetail'